### ISSUE TITLE
Provide ipxe script for installed machines

### ISSUE THREAD

**Issue by smaftoul** [giantswarm/mayu#14]
Currently, mayu generates `dhcp-ignores` clauses in dnsmasq's configuration for bootstrapped hosts.
These hosts' bioses are configured to boot on the network.
Once bootstrapped, if you reboot, it tries to boot on the network and takes ages to timeout (further more if you have several network interfaces in your machines).
Mayu could provide pxe / dhcp / ipxe script to these machines to simply chain load the normal boot, something like `sanboot --no-describe --drive 0x80`.

**Comment by calvix** [comment]
with the ignition in place we wont be needing this
