### ISSUE TITLE
Document machine states

### ISSUE THREAD

**Issue by smaftoul** [giantswarm/mayu#15]
Documentation is missing a state diagram or flowchart of machines lifecycle to better understand how mayu works.

**Comment by hectorj2f** [comment]
![statesmayu](https://cloud.githubusercontent.com/assets/3602792/14924458/5e549986-0e4b-11e6-9d16-1432234bc29a.jpg)

Do you agree with the state transitions ?
ping @teemow @htr

**Comment by teemow** [comment]
LGTM

**Comment by hectorj2f** [comment]
Addressed in https://github.com/giantswarm/mayu/pull/52
