### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/mayu#26]
CONTRIBUTING.md has not been updated from the template - e.g: it should refer to "Mayu" instead of "PROJECT"

**Comment by teemow** [comment]
This has been fixed by @puja108 

https://github.com/giantswarm/mayu/commit/cae6389820385369478fcb962d288f656968a6da

**Comment by puja108** [comment]
yup, sorry for editing in master
