### ISSUE TITLE
Check why mayu is not updating leaseweb-cluster repo

### ISSUE THREAD

**Issue by hectorj2f** [giantswarm/mayu#53]
https://github.com/giantswarm/leaseweb-cluster

Related to:
https://gigantic.slack.com/archives/incidents/p1464124261000570
https://gigantic.slack.com/archives/ops/p1464124288000586

**Comment by hectorj2f** [comment]
Related to https://github.com/giantswarm/management-ansible/issues/10

**Comment by teemow** [comment]
Fixed!
