### ISSUE TITLE
Clarification of README

### ISSUE THREAD

**Issue by danehans** [giantswarm/mayu#54]
The README states:

>  It sets up fleet meta-data, and patched versions of fleet, etcd, and docker when using Yochu.

Can you help me understand why fleet, etcd, and docker need to be patched for Mayu? I'm interested in evaluating the project, but have concerns using patched versions of fleet, etcd, and docker. If you are patching these pieces of software, have you submitted PR's to merge the patches upstream?

**Comment by hectorj2f** [comment]
Hi @danehans 

Generally, those versions are specified cause another of our tools named `yochu` http://github.com/giantswarm/yochu, is in charge of installing those versions. Nevertheless you can omit the usage of yochu in the config, and thereby you could skip this part if you wish.

However, we saw several scenarios where you would like to have control of the installed versions:

1) You might not want to use the latest version of docker shipped within the specified CoreOS version. It could be that you saw some bugs upstream, or your software is not ready for these new versions.
    As an example, we just do this for etcd, docker...

2) You might have developed a newer version. As an example, we are doing this for fleet http://github.com/giantswarm/fleet, https://github.com/coreos/fleet/pull/1426

**Comment by danehans** [comment]
@hectorj2f thanks for the feedback. I now have a better understanding of the issue. Mayu can be used with or without Yochu. Yochu is the piece that implements patched versions of etcd, fleet, etc..

I can see the benefits that you describe above. I have been using the [Kubernetes Ansible](https://github.com/kubernetes/contrib/tree/master/ansible) project, which includes mechanisms for managing software installation details similar to what you describe above.

**Comment by hectorj2f** [comment]
@danehans You're welcomed. 

In fact, you can currently install a specific kubectl version. In a close future, we'll add our scripts for a Kubernetes setup.

**Comment by danehans** [comment]
I consider this issue closed. Thanks again for the clarification.
