### ISSUE TITLE
Use systemd-resolved

### ISSUE THREAD

**Issue by teemow** [giantswarm/mayu#68]
Currently we are writing out a `resolv.conf` in the cloudconfig/ignition templates. But we should change this to use `systemd-resolved`

See:
https://github.com/giantswarm/mayu/blob/master/templates/last_stage_cloudconfig.yaml#L96
https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html

**Comment by calvix** [comment]
we define DNS via systemd-networkd so i think we are fine to close this
