### ISSUE TITLE
CoreOS -> CoreOS Container Linux

### ISSUE THREAD

**Issue by philips** [giantswarm/mayu#86]
CoreOS Linux was renamed to CoreOS Container Linux. Can you please refer to CoreOS as CoreOS Container Linux or simply Container Linux?

Thank you!

https://coreos.com/blog/tectonic-self-driving.html#coreos-linux-is-now-container-linux

**Comment by calvix** [comment]
Should be easy, @r7vme can you take a look ?

**Comment by r7vme** [comment]
sure, i'll take that
