### ISSUE TITLE
Docker Image and mayu layout

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/mayu#9]
_From @teemow on January 28, 2016 21:5_

During the release of bootxe 0.6.0 I had a look at the Dockerfile. There are two things in there that I think need to be fixed before releasing bootxe. 

1) The config is at `/opt/bootxe/config/config.yaml` but the new default is at `/etc/bootxe/config.yaml`. Why not using the new location?
2) We are copying the whole bin-dist folder into the container. Since you don't want to create a new bootxe release for every new coreos image we should probably leave the images outside of the container in a volume. this would also make the image much smaller.

Thoughts but minor (not necessary _before_ the release):
* It would be easier to reconfigure bootxe within the container if we can set all config parameter through environment/arguments. I would consider that as a best practice anyway.

Some more thoughts:
* bootxe is at `/opt/bootxe/bootxe` but should be at `/usr/bin/bootxe`. 
* we should also take care that default templates are at `/usr/lib/bootxe` and you can overwrite it via `/etc/bootxe`[1]
* same (default in /usr/lib / overwrite in /etc) should work for the config[1]
* same goes for static_html, images and tftproot. but it might be worth thinking if it also fits for `/var/lib/bootxe` especially if you look at 2).
* the `cluster` information should definitely go into `/var/lib/bootxe`

[1] think of a factory reset of machines (see http://0pointer.net/blog/projects/stateless.html)

_Copied from original issue: giantswarm/bootxe#101_

**Comment by teemow** [comment]
Some of the points are fixed in #28

**Comment by teemow** [comment]
Created separate issues for the rest in the issue. See #30, #31
