### ISSUE TITLE
etcd datastore for mayu

### ISSUE THREAD

**Issue by calvix** [giantswarm/mayu#95]
Currently data about machines are stored on disk, storing this data in etcd make more sense.

**Comment by r7vme** [comment]
@calvix i can pick this up from next week

**Comment by calvix** [comment]
Cool, i will give you some more info later.

**Comment by JosephSalisbury** [comment]
As an fyi, we have a fairly robust storage implementation in microkit - https://github.com/giantswarm/microkit/blob/master/storage/storage.go

I could see that being useful here

**Comment by calvix** [comment]
this should be mostly place where al the storage thing happens
https://github.com/giantswarm/mayu/tree/master/hostmgr

if you wanna see how it looks in real-case check our mayu host in LW
